cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string
  connection_string: ${DATABASE_URL}

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  auto_publish: false

  # Associative arrays of table sources
  tables:

    # --- Shared --- #

    # railway_line_high, see function below

    # --- Standard --- #

    standard_railway_text_stations_low:
      schema: public
      table: standard_railway_text_stations_low
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: string
        feature: string
        state: string
        station: string
        station_size: string
        label: string
        name: string
        uic_ref: string
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    standard_railway_text_stations_med:
      schema: public
      table: standard_railway_text_stations_med
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: string
        feature: string
        state: string
        station: string
        station_size: string
        label: string
        name: string
        uic_ref: string
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    standard_railway_turntables:
      schema: public
      table: turntables
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        osm_id: integer
        feature: string

    standard_station_entrances:
      schema: public
      table: station_entrances
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        osm_id: integer
        type: string
        name: string
        ref: string
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    standard_railway_text_stations:
      schema: public
      table: standard_railway_text_stations
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      minzoom: 8
      properties:
        id: integer
        osm_id: string
        feature: string
        state: string
        station: string
        station_size: string
        label: string
        name: string
        count: integer
        uic_ref: string
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    standard_railway_grouped_stations:
      schema: public
      table: standard_railway_grouped_stations
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        osm_id: string
        feature: string
        state: string
        station: string
        label: string
        name: string
        uic_ref: string
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    railway_text_km:
      schema: public
      table: railway_text_km
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        pos: string
        pos_int: string
        zero: boolean
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    standard_railway_switch_ref:
      schema: public
      table: standard_railway_switch_ref
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        ref: string
        type: string
        turnout_side: string
        local_operated: boolean
        resetting: boolean
        wikidata: string
        wikimedia_commons: string
        image: string
        mapillary: string
        wikipedia: string
        note: string
        description: string

    # --- Speed --- #

    # speed_railway_signals, see function below

    # --- Signals --- #

    # signals_signal_boxes, see function below
    # signals_railway_signals, see function below

    # --- Electrification --- #

    # electrification_signals, see function below

    catenary:
      schema: public
      table: electrification_catenary
      srid: 3857
      geometry_column: way
      geometry_type: GEOMETRY
      properties:
        id: integer
        osm_id: integer
        osm_type: string
        ref: string
        feature: string
        position: string
        structure: string
        supporting: string
        attachment: string
        tensioning: string
        insulator: string
        note: string
        description: string

  functions:

    # --- Shared --- #

    railway_line_high:
      schema: public
      function: railway_line_high
      maxzoom: 14

    # --- Standard --- #

    standard_railway_symbols:
      schema: public
      function: standard_railway_symbols
      minzoom: 10

    # --- Speed --- #

    speed_railway_signals:
      schema: public
      function: speed_railway_signals
      minzoom: 13

    # --- Signals --- #

    signals_signal_boxes:
      schema: public
      function: signals_signal_boxes
      minzoom: 8
      maxzoom: 14

    signals_railway_signals:
      schema: public
      function: signals_railway_signals
      minzoom: 13

    # --- Electrification --- #

    electrification_signals:
      schema: public
      function: electrification_signals
      minzoom: 13

    electrification_railway_symbols:
      schema: public
      function: electrification_railway_symbols
      minzoom: 13

fonts:
  - /config/fonts
