cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string
  connection_string: ${DATABASE_URL}

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  auto_publish: false

  # Associative arrays of table sources
  tables:

    # --- Shared --- #

    railway_line_low:
      schema: public
      table: railway_line_low
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        # TODO calculate labels in frontend
        id: integer
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: boolean
        tunnel: boolean
        bridge: boolean
        ref: string
        standard_label: string
        track_ref: string
        maxspeed: number
        speed_label: string
        train_protection: string
        train_protection_rank: integer
        electrification_state: string
        frequency: number
        voltage: number
        future_frequency: number
        future_voltage: number
        electrification_label: string
        gauge0: string
        gaugeint0: number
        gauge1: string
        gaugeint1: number
        gauge2: string
        gaugeint2: number
        gauge_label: string
        reporting_marks: string

    railway_line_med:
      schema: public
      table: railway_line_med
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        # TODO calculate labels in frontend
        id: integer
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: boolean
        tunnel: boolean
        bridge: boolean
        ref: string
        standard_label: string
        track_ref: string
        maxspeed: number
        speed_label: string
        train_protection: string
        train_protection_rank: integer
        electrification_state: string
        frequency: number
        voltage: number
        future_frequency: number
        future_voltage: number
        electrification_label: string
        gauge0: string
        gaugeint0: number
        gauge1: string
        gaugeint1: number
        gauge2: string
        gaugeint2: number
        gauge_label: string
        reporting_marks: string

    railway_line_high:
      schema: public
      table: railway_line_high
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        # TODO calculate labels in frontend
        id: integer
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: boolean
        tunnel: boolean
        bridge: boolean
        ref: string
        standard_label: string
        track_ref: string
        maxspeed: number
        speed_label: string
        train_protection: string
        train_protection_rank: integer
        electrification_state: string
        frequency: number
        voltage: number
        future_frequency: number
        future_voltage: number
        electrification_label: string
        gauge0: string
        gaugeint0: number
        gauge1: string
        gaugeint1: number
        gauge2: string
        gaugeint2: number
        gauge_label: string
        reporting_marks: string

    # --- Standard --- #

    standard_railway_text_stations_low:
      schema: public
      table: standard_railway_text_stations_low
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        label: string

    standard_railway_text_stations_med:
      schema: public
      table: standard_railway_text_stations_med
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        label: string

    standard_railway_turntables:
      schema: public
      table: turntables
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        feature: string

    standard_railway_text_stations:
      schema: public
      table: standard_railway_text_stations
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        railway: string
        station: string
        label: string
        name: string

    standard_railway_symbols:
      schema: public
      table: standard_railway_symbols
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        feature: string

    standard_railway_text_km:
      schema: public
      table: standard_railway_text_km
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        railway: string
        pos: string
        zero: boolean

    standard_railway_switch_ref:
      schema: public
      table: standard_railway_switch_ref
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        railway: string
        ref: string
        # TODO: rename local_operated
        railway_local_operated: boolean

    # --- Speed --- #

    speed_railway_signals:
      schema: public
      table: speed_railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        feature: string
        type: string
        azimuth: number
        direction_both: boolean

    # --- Signals --- #

    signals_railway_signals:
      schema: public
      table: signals_railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        railway: string
        ref: string
        ref_multiline: string
        feature: string
        deactivated: boolean
        azimuth: number
        direction_both: boolean

    signals_signal_boxes:
      schema: public
      table: signals_signal_boxes
      srid: 3857
      geometry_column: way
      geometry_type: GEOMETRY
      properties:
        id: integer
        feature: string
        ref: string
        name: string

    # --- Electrification --- #

    electrification_signals:
      schema: public
      table: electrification_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        feature: string
        azimuth: number
        direction_both: boolean

fonts:
  - /config/fonts
