cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string. You can use env vars too, for example:
  #   $DATABASE_URL
  #   ${DATABASE_URL:-postgresql://postgres@localhost/db}
  connection_string: ${DATABASE_URL}

  # # Same as PGSSLCERT for psql
  # ssl_cert: './postgresql.crt'
  # # Same as PGSSLKEY for psql
  # ssl_key: './postgresql.key'
  # # Same as PGSSLROOTCERT for psql
  # ssl_root_cert: './root.crt'

  # #  If a spatial table has SRID 0, then this SRID will be used as a fallback
  # default_srid: 4326

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  # auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  # auto_publish: false

  # Associative arrays of table sources
  tables:

    # --- Standard --- #

    railway_line_low:
      schema: public
      table: railway_line_low
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: string
        tunnel: boolean
        bridge: boolean

    railway_line_med:
      schema: public
      table: railway_line_med
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: string
        tunnel: boolean
        bridge: boolean

    railway_turntables:
      schema: public
      table: railway_turntables
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        railway: string

    railway_line_fill:
      schema: public
      table: railway_line_fill
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        highspeed: string
        tunnel: boolean
        bridge: boolean

    railway_text_stations_med:
      schema: public
      table: railway_text_stations_med
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        station: string
        label: string

    railway_text_stations_high:
      schema: public
      table: railway_text_stations_high
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        station: string
        label: string

    railway_symbols:
      schema: public
      table: railway_symbols
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        man_made: string

    railway_text_med:
      schema: public
      table: railway_text_med
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        label: string

    railway_text_high:
      schema: public
      table: railway_text_high
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        label: string

    railway_text_km_med:
      schema: public
      table: railway_text_km_med
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        pos: string

    railway_text_km_high:
      schema: public
      table: railway_text_km_high
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        pos: string

    railway_switch_ref:
      schema: public
      table: railway_switch_ref
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        ref: string
        railway_local_operated: string

    railway_text_detail:
      schema: public
      table: railway_text_detail
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        usage: string
        service: string
        label: string
        track_ref: string

    # --- Signalling --- #

    railway_line:
      schema: public
      table: railway_line
      srid: 3857
      geometry_column: way
      geometry_type: LINESTRING
      properties:
        railway: string
        feature: string
        usage: string
        service: string
        layer: number
        rank: number
        train_protection: string

    railway_signals:
      schema: public
      table: railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        railway: string
        ref: string
        feature: string
        deactivated: boolean

    signal_boxes_point:
      schema: public
      table: signal_boxes_point
      srid: 3857
      geometry_column: way
      geometry_type: POINT

    signal_boxes_polygon:
      schema: public
      table: signal_boxes_polygon
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON

    signal_boxes_text:
      schema: public
      table: signal_boxes_text
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        ref: string
        name: string

fonts:
  - /config/fonts
