version: 2.1

executors:
  default:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

jobs:
  import-data:
    executor: default
    steps:
      - checkout
      - run: curl -L https://fly.io/install.sh | sh
      - run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin
      - run: docker compose pull db
      - run: docker image ls ghcr.io/hiddewie/openrailwaymap-import-db:latest
      - run: docker compose up --no-build --pull never --wait db
      - run: docker compose build import
      - run:
          no_output_timeout: 1h
          environment:
            OSM2PGSQL_CACHE: '7000'
            OSM2PGSQL_NUMPROC: '2'
          command: docker compose run import update
      - run: docker compose push import
      - run: |
          docker compose stop db
          DB_CONTAINER_ID="$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .ID')"
          DB_IMAGE="$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .Image')"
          
          # Persist and squash data in new image
          docker cp "$DB_CONTAINER_ID:/var/lib/postgresql/postgres-data" db/postgres-data
          echo 'COPY postgres-data /var/lib/postgresql/postgres-data' >> db/Dockerfile
          echo '!db/postgres-data' >> .dockerignore
          
          docker compose build db
          docker compose push db
      - run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/hiddewie/OpenRailwayMap-vector/actions/workflows/deploy.yml/dispatches \
            -d "$(jq -c -n --arg branch "$CIRCLE_BRANCH" '{ref: $branch}')"

workflows:
  auto-deployment:
    jobs:
      - import-data:
          context:
            - github
