name: Deploy

on:
  workflow_dispatch: ~

jobs:
  deploy-proxy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    environment: proxy-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Manually write import bounds, to decouple proxy from tile generation/import
      - name: Output import bounds
        run: |
          echo '[[-10.0, 35.7], [39.0, 70.0]]' > data/import/bounds.json

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config proxy.fly.toml --local-only

  generate-tiles:
    name: Generate tiles
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tiles:
          - low-med
          - high
          - standard
          - speed
          - signals
          - electrification

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull database
        run: |
          docker compose pull db
          docker compose up --no-build --pull never --wait db

      - name: Generate tiles
        env:
          TILES: ${{ matrix.tiles }}
          BBOX: '-10.0,35.7,39.0,70.0'
        run: |
          docker compose run martin-cp
          ls -las tiles/

      - uses: actions/upload-artifact@v4
        with:
          name: tiles-${{ matrix.tiles }}
          path: |
            tiles/*.mbtiles
          if-no-files-found: error
          retention-days: 3

  deploy-tiles:
    name: Deploy tiles
    runs-on: ubuntu-latest
    needs: generate-tiles
    environment: tiles-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          # No name: download everything
          path: tiles
          merge-multiple: true

      - name: List generated tiles
        run: |
          ls -lah tiles/

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config martin-static.fly.toml --local-only

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: api-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull database
        run: |
          docker compose pull db
          docker compose up --no-build --pull never --wait db

      - name: Prepare and build API container
        env:
          SKIP_CLEANUP: 'yes'
        run: |
          api/prepare-api.sh

      - name: Print import logs
        if: ${{ always() }}
        run: |
          docker compose logs api-import

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config api.fly.toml --local-only api
