name: Deploy Tiles

on:
  workflow_call:
    inputs:
      region:
        type: string
        required: true
        description: "Region to generate tiles for"
    secrets:
      FLY_API_TOKEN:
        required: true

jobs:
  tiles-bboxes:
    name: Generate bounding boxes
    runs-on: ubuntu-latest

    outputs:
      bboxes: ${{ steps.bboxes.outputs.bboxes }}
      matrix: ${{ steps.bboxes.outputs.matrix }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: bboxes
        run: |
          {
            echo -n 'matrix='
            jq --arg region '${{ inputs.region }}' -c '{ bbox: .[$region].bboxes }' tiles/deploy-bboxes.json
          } >> $GITHUB_OUTPUT
          
          {
            echo -n 'bboxes='
            jq --arg region '${{ inputs.region }}' -r '.[$region].bboxes[]' tiles/deploy-bboxes.json | tr '\n' ' '
          } >> $GITHUB_OUTPUT

  generate-tiles:
    name: Generate tiles
    runs-on: ubuntu-latest

    needs:
      - tiles-bboxes

    strategy:
      matrix: ${{ fromJson(needs.tiles-bboxes.outputs.matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull database
        run: |
          docker compose pull db
          docker compose up --no-build --pull never --wait db

      - name: Generate tiles
        env:
          TILES: high
          BBOX: ${{ matrix.bbox }}
        run: |
          docker compose run --no-deps martin-cp

          mkdir -p "tiles/split/${{ matrix.bbox }}"
          mv tiles/*.mbtiles "tiles/split/${{ matrix.bbox }}"

      - name: List generated tiles
        run: |
          ls -lah tiles/split/${{ matrix.bbox }}/*.mbtiles

      - uses: actions/upload-artifact@v4
        with:
          name: tiles-${{ inputs.region }}-${{ matrix.bbox }}
          path: |
            tiles/split
          if-no-files-found: error
          retention-days: 3

  deploy-tiles:
    name: Merge and deploy tiles
    runs-on: ubuntu-latest

    needs:
      - tiles-bboxes
      - generate-tiles

    environment: tiles-production-${{ inputs.region }}

    env:
      BBOXES: ${{ needs.tiles-bboxes.outputs.bboxes }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PMTiles
        uses: ./.github/actions/setup-pmtiles

      - uses: actions/download-artifact@v4
        with:
          pattern: tiles-${{ inputs.region }}-*
          merge-multiple: true
          path: tiles/split

      - name: Merge tiles
        run: |
          docker compose run --entrypoint /tiles/merge.sh -e BBOXES --no-deps martin-cp

      - name: Delete split tiles
        run: |
          for bbox in $BBOXES; do
            rm -rf "tiles/split/$bbox"
          done

      - name: List generated MBTiles
        run: |
          ls -lah tiles/*.mbtiles

      - name: Convert MBTiles to PMTiles
        run: |
          for file in tiles/*.mbtiles
          do 
            pmtiles convert "$file" "$(echo "$file" | sed 's/mbtiles$/pmtiles/')" || true
            rm -f "$file"
          done

      - name: List generated PMTiles
        run: |
          ls -lah tiles/*.pmtiles

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --app openrailwaymap-tiles-${{ inputs.region }} --config martin-static.fly.toml --local-only
