name: Nightly update

on:
  workflow_dispatch: ~
  schedule:
    # Run daily at 17:47 UTC
    - cron: '47 17 * * *'

jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull OSM data
        run: |
          docker compose pull data
          docker compose create data
          docker compose cp data:/data/data.osm.pbf data/filtered/data.osm.pbf

      - name: Build import image
        run: |
          docker compose build import

      - name: Update OSM data
        run: |
          docker compose run --no-deps import update

      - name: Build new OSM data image
        run: |
          docker compose build data

      - name: Push OSM data
        run: |
          docker compose push data

      - name: Build database
        run: |
          docker compose build db

      - name: Start database
        run: |
          docker compose up --wait db
          docker inspect "$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .ID')"
          # No idea why this is needed, DB should be healthy by now
          sleep 10
          docker inspect "$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .ID')"

      - name: Import data
        env:
          OSM2PGSQL_NUMPROC: '8'
        run: |
          docker compose run import import

      - name: Push data
        run: |
          docker compose stop db
          DB_CONTAINER_ID="$(docker compose ps --all --format json | jq -r 'select(.Service == "db") | .ID')"
          docker commit "$DB_CONTAINER_ID" ghcr.io/hiddewie/openrailwaymap-import-db:latest
          docker compose push db

      - name: Trigger deployment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run --ref '${{ github.ref_name }}' deploy.yml
